CREATE TABLE `shops` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`initials` text NOT NULL,
	`logo` text DEFAULT '' NOT NULL,
	`logo_text` text DEFAULT '' NOT NULL,
	`logo_background` text DEFAULT 'light' NOT NULL,
	`type` text DEFAULT '' NOT NULL,
	`product_range` text DEFAULT '' NOT NULL,
	`price_range` text DEFAULT '' NOT NULL,
	`contact` text DEFAULT '' NOT NULL,
	`fit` text DEFAULT '' NOT NULL,
	`address` text NOT NULL,
	`neighborhood` text DEFAULT '' NOT NULL,
	`website` text DEFAULT '' NOT NULL,
	`directions_url` text DEFAULT '' NOT NULL,
	`lat` real NOT NULL,
	`lng` real NOT NULL,
	`note` text DEFAULT '' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
